// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_TzGcxYlxKFyR0enELJKu_oKxE0eAJ-Y',
    appId: '1:373499221917:web:bb0d6ff1621a4b32808174',
    messagingSenderId: '373499221917',
    projectId: 'project-hail-mary-45d30',
    authDomain: 'project-hail-mary-45d30.firebaseapp.com',
    storageBucket: 'project-hail-mary-45d30.firebasestorage.app',
    measurementId: 'G-5KM12RP2VV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDKAMA7NPQpbjuEeN2yTvcgMv4jlYf11o',
    appId: '1:373499221917:android:109d61bf94d2a4a0808174',
    messagingSenderId: '373499221917',
    projectId: 'project-hail-mary-45d30',
    storageBucket: 'project-hail-mary-45d30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5eceuMAJBY86G3qpt0tZ4H8D6js-uDVE',
    appId: '1:373499221917:ios:4cf01bfb9b6ac605808174',
    messagingSenderId: '373499221917',
    projectId: 'project-hail-mary-45d30',
    storageBucket: 'project-hail-mary-45d30.firebasestorage.app',
    iosBundleId: 'com.example.projecthealclinic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_TzGcxYlxKFyR0enELJKu_oKxE0eAJ-Y',
    appId: '1:373499221917:web:5cd3a0183ab3ed84808174',
    messagingSenderId: '373499221917',
    projectId: 'project-hail-mary-45d30',
    authDomain: 'project-hail-mary-45d30.firebaseapp.com',
    storageBucket: 'project-hail-mary-45d30.firebasestorage.app',
    measurementId: 'G-3KD19P3G69',
  );
}
